language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
install:
  - npm install
#before_script:
script: npm test
#after_success:
#after_failure:
#before_deploy:
# deploy:
# 	skip_cleanup: true
#after_deploy:
#after_script:
branches:
  only:
    - master
    - develop